# Generated by Django 5.2.3 on 2025-08-17 16:07

import django.db.models.deletion
import sorl.thumbnail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Например, Диаметр', max_length=100, verbose_name='Название')),
                ('unit', models.CharField(blank=True, default='мм, кг, л и т. п.', max_length=20, verbose_name='Единица измерения')),
                ('data_type', models.CharField(default='Например, string', max_length=20, verbose_name='Тип данных')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
            ],
            options={
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибуты',
            },
        ),
        migrations.CreateModel(
            name='SparePartType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название типа')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='spare_part_types/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
            ],
            options={
                'verbose_name': 'Тип запчасти',
                'verbose_name_plural': 'Типы запчастей',
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('installed', 'Установлено'), ('stock', 'На складе'), ('repair', 'В ремонте'), ('wait_repair', 'Ожидает ремонт')], default='stock', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_parts', to='vehicle.vehicle', verbose_name='Техника')),
                ('spareparttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='spare_part.spareparttype', verbose_name='Тип запчасти')),
            ],
            options={
                'verbose_name': 'Запчасть',
                'verbose_name_plural': 'Запчасти',
            },
        ),
        migrations.CreateModel(
            name='SparePartChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='Действие')),
                ('field_name', models.CharField(blank=True, max_length=50, verbose_name='Поле')),
                ('old_value', models.TextField(blank=True, verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, verbose_name='Новое значение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='spare_part.sparepart', verbose_name='Запчасть')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог изменения запчасти',
                'verbose_name_plural': 'Логи изменений запчастей',
            },
        ),
        migrations.CreateModel(
            name='SparePartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', sorl.thumbnail.fields.ImageField(upload_to='sparepart_images/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='spare_part.sparepart', verbose_name='Запчасть')),
            ],
            options={
                'verbose_name': 'Изображение запчасти',
                'verbose_name_plural': 'Изображения запчастей',
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, verbose_name='Значение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='spare_part.attribute', verbose_name='Атрибут')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='spare_part.sparepart', verbose_name='Запчасть')),
            ],
            options={
                'verbose_name': 'Значение атрибута',
                'verbose_name_plural': 'Значения атрибутов',
                'unique_together': {('spare_part', 'attribute')},
            },
        ),
        migrations.CreateModel(
            name='AttributeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательный')),
                ('default_value', models.CharField(blank=True, max_length=255, verbose_name='Значение по умолчанию')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='spare_part.attribute', verbose_name='Атрибут')),
                ('spare_part_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_templates', to='spare_part.spareparttype', verbose_name='Тип запчасти')),
            ],
            options={
                'verbose_name': 'Шаблон атрибута',
                'verbose_name_plural': 'Шаблоны атрибутов',
                'unique_together': {('spare_part_type', 'attribute')},
            },
        ),
    ]
